
trigger:
- main

pool:
  name: GCC_MIUN_VMSS
  vmImage: Canonical:0001-com-ubuntu-confidential-vm-focal:20_04-lts-gen2:latest

jobs:
- job: buildLeanMsr
  displayName: Build Lean MSR
  steps:

  - script: |
      chmod u+x ${BUILD_SOURCESDIRECTORY}/"*.sh
      ${BUILD_SOURCESDIRECTORY}/getBuildah.sh
    displayName: 'Update and get Buildah'

  - task: DownloadSecureFile@1
    name: msrLicense
    displayName: 'Download MSR license'
    inputs:
      secureFile: 'msr-license.xml'

  - task: DownloadSecureFile@1
    name: secrets
    displayName: 'Download MSR build secrets'
    inputs:
      secureFile: 'msr.build.secrets.sh'

  - script: |
      echo "Dumping environment"
      env | sort
      echo "End nvironment dump"
      echo "Running a repository script"
      chmod u+x ${BUILD_SOURCESDIRECTORY}/scripts/*.sh
      ${BUILD_SOURCESDIRECTORY}/scripts/buildSagImages.sh
    displayName: 'Generate Lean MSR container image'